name: Validate JSONs and Automerge

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "src/data.json"

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: src/schema.json
          INPUT_JSONS: src/data.json
      - name: Merge Pull Request
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          script: |
            const { context } = require("@actions/github");
            const octokit = new Octokit();
            const prNumber = context.payload.pull_request.number;
            const mergeResponse = await octokit.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "squash",
            });
            console.log(`PR ${prNumber} merged successfully:`, mergeResponse);
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
