name: Validate JSON

on:
  push:
    paths:
      - "src/data.json"

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Validate JSON
        run: |
          JSON_FILE=src/data.json
          SCHEMA_FILE=src/schema.json
          JSON_SCHEMA=$(cat $SCHEMA_FILE)
          JSON_DATA=$(cat $JSON_FILE)
          python -c "import jsonschema; jsonschema.validate(json.loads('$JSON_DATA'), json.loads('$JSON_SCHEMA'))"

      - name: Set output
        if: ${{ job.status == 'success' }}
        run: echo "JSON file is valid!"
        shell: bash
        env:
          VALIDATED: "true"

      - name: Set output
        if: ${{ job.status != 'success' }}
        run: echo "JSON file is not valid!"
        shell: bash
        env:
          VALIDATED: "false"
