name: Validate JSON Syntax

on:
  push:
    branches:
      - main
    paths:
      - 'src/data.json'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /path/to/schema.json
          INPUT_JSONS: /path/to/file.json,/path/to/another/file.json

      - name: Fail workflow on validation error
        if: ${{ failure() }}
        run: exit 1
